### ISSUE TITLE
Purchase Details Not Found. Contact Administrator.

### ISSUE THREAD

**Issue by ghost** [kidino/simple-ipn#1]
There is a problem when viewing the downloads page. After a transaction the customer details are shown correctly however when clicking on the download link it keeps throwing error "Purchase Details Not Found. Contact Administrator." and is not creating any additional files to store customer data. I have tried everything to get this to work including chmoding files, manually creating a customer file however no luck. Any advice?

**Comment by kidino** [comment]
Sorry for not being active in developing this. But I just made an update that includes
- handling new changes to data sent to thank you page
- updating Paypal IPN URL to ipnpb.paypal.com
- Paypal IPN verification with HTTP/1.1

See if this works for you.
